import { useMemo, useState, useEffect } from "react";
import { useDataContext } from "../../Context/DataContext";
import {
  Card,
  Text,
  Group,
  ScrollArea,
  TextInput,
  Button,
  Title,
  Stack,
  Select,
} from "@mantine/core";
import Table from "../../../lib/AppTable";
import { formatCurrency, formatDate } from "../../../lib/format-utils";
import { Search, RefreshCw, MoreVertical } from "lucide-react";
import openPrintWindow from "../../../components/print/printWindow";
import type { InvoiceData } from "../../../components/print/printTemplate";
import { getAllJournalVouchers, createJournalVoucher } from "../../../lib/api";
import { notifications } from "@mantine/notifications";

type JournalVoucher = {
  id: string;
  voucherNumber: string;
  voucherDate: string | Date;
  particulars: string;
  debitAccount: string;
  creditAccount: string;
  amount: number;
  remarks?: string;
};

export default function JournalVouchersPage() {
  const { customers, suppliers } = useDataContext();
  const [q, setQ] = useState("");
  const [data, setData] = useState<JournalVoucher[]>([]);
  const [loading, setLoading] = useState(false);
  // For dynamic mapping UI
  const [particulars, setParticulars] = useState("");
  const [debitAccount, setDebitAccount] = useState("");
  const [creditAccount, setCreditAccount] = useState("");
  const [amount, setAmount] = useState<number>(0);
  const [selectedCustomer, setSelectedCustomer] = useState<string>("");
  const [selectedSupplier, setSelectedSupplier] = useState<string>("");

  useEffect(() => {
    getAllJournalVouchers().then((vouchers: unknown[] = []) => {
      const mapped: JournalVoucher[] = (vouchers || []).map((v: unknown) => {
        if (typeof v === "object" && v !== null) {
          const obj = v as Record<string, unknown>;
          let voucherDate: string | Date = "";
          if (obj.voucherDate instanceof Date) {
            voucherDate = obj.voucherDate;
          } else if (typeof obj.voucherDate === "string") {
            voucherDate = obj.voucherDate;
          } else {
            voucherDate = "";
          }
          return {
            id: String(
              obj._id ||
                obj.id ||
                obj.voucherNumber ||
                Math.random().toString(36).slice(2)
            ),
            voucherNumber: String(obj.voucherNumber ?? ""),
            voucherDate,
            particulars: String(obj.particulars ?? ""),
            debitAccount: String(obj.debitAccount ?? ""),
            creditAccount: String(obj.creditAccount ?? ""),
            amount: Number(obj.amount ?? 0),
            remarks: obj.remarks ? String(obj.remarks) : undefined,
          };
        }
        // fallback for unexpected types
        return {
          id: Math.random().toString(36).slice(2),
          voucherNumber: "",
          voucherDate: "",
          particulars: "",
          debitAccount: "",
          creditAccount: "",
          amount: 0,
        };
      });
      setData(mapped);
    });
  }, []);

  const filtered = useMemo(() => {
    const t = q.toLowerCase().trim();
    if (!t) return data;
    return data.filter(
      (v) =>
        v.voucherNumber.toLowerCase().includes(t) ||
        v.particulars.toLowerCase().includes(t) ||
        v.debitAccount.toLowerCase().includes(t) ||
        v.creditAccount.toLowerCase().includes(t)
    );
  }, [q, data]);

  // Example: Generate journal vouchers on the frontend using mapping logic
  const handleFrontendGenerate = async () => {
    if (
      !particulars ||
      !debitAccount ||
      !creditAccount ||
      !amount ||
      amount <= 0
    ) {
      notifications.show({
        color: "red",
        title: "Missing Fields",
        message: "Please fill all fields and enter a valid amount.",
      });
      return;
    }
    setLoading(true);
    const newVoucher = {
      voucherNumber: `JV-${(data.length + 1).toString().padStart(4, "0")}`,
      voucherDate: new Date().toISOString(),
      particulars,
      debitAccount,
      creditAccount,
      amount,
      remarks: "Auto-generated by frontend logic",
    };
    try {
      await createJournalVoucher(newVoucher);
      notifications.show({
        color: "green",
        title: "Success",
        message: "Journal voucher generated and saved!",
      });
      // Clear fields
      setParticulars("");
      setDebitAccount("");
      setCreditAccount("");
      setAmount(0);
    } catch (e) {
      notifications.show({
        color: "red",
        title: "Error",
        message: "Failed to save journal voucher.",
      });
    }
    // Refresh list
    const vouchers = await getAllJournalVouchers();
    const mapped: JournalVoucher[] = (vouchers || []).map((v: unknown) => {
      if (typeof v === "object" && v !== null) {
        const obj = v as Record<string, unknown>;
        let voucherDate: string | Date = "";
        if (obj.voucherDate instanceof Date) {
          voucherDate = obj.voucherDate;
        } else if (typeof obj.voucherDate === "string") {
          voucherDate = obj.voucherDate;
        } else {
          voucherDate = "";
        }
        return {
          id: String(
            obj._id ||
              obj.id ||
              obj.voucherNumber ||
              Math.random().toString(36).slice(2)
          ),
          voucherNumber: String(obj.voucherNumber ?? ""),
          voucherDate,
          particulars: String(obj.particulars ?? ""),
          debitAccount: String(obj.debitAccount ?? ""),
          creditAccount: String(obj.creditAccount ?? ""),
          amount: Number(obj.amount ?? 0),
          remarks: obj.remarks ? String(obj.remarks) : undefined,
        };
      }
      return {
        id: Math.random().toString(36).slice(2),
        voucherNumber: "",
        voucherDate: "",
        particulars: "",
        debitAccount: "",
        creditAccount: "",
        amount: 0,
      };
    });
    setData(mapped);
    setLoading(false);
  };

  return (
    <div style={{ display: "grid", gap: 20 }}>
      <Group justify="apart" align="center">
        <div>
          <Title order={2}>Journal Vouchers</Title>
          <Text size="sm" color="dimmed">
            Record all journal entries (debits and credits)
          </Text>
        </div>
      </Group>

      <Group justify="space-between" align="center">
        <Group>
          <Stack gap={0}>
            <Text fw={600}>All Journal Vouchers</Text>
            <Text size="sm" c="dimmed">
              {filtered.length} found
            </Text>
          </Stack>
        </Group>
        <Group>
          <TextInput
            placeholder="Search journal vouchers..."
            value={q}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
              setQ(e.currentTarget.value)
            }
            leftSection={<Search size={16} style={{ color: "gray" }} />}
          />
        </Group>
      </Group>

      {/* Dynamic mapping UI for voucher generation */}
      <Card withBorder shadow="sm" mb={20} p={16} style={{ maxWidth: 600 }}>
        <Stack gap={8}>
          <Title order={4}>Generate Journal Voucher (Frontend)</Title>
          <TextInput
            label="Particulars"
            value={particulars}
            onChange={(e) => setParticulars(e.currentTarget.value)}
            placeholder="e.g. Monthly Salary Accrual"
            required
          />
          <TextInput
            label="Amount"
            type="number"
            value={amount || ""}
            onChange={(e) => setAmount(Number(e.currentTarget.value))}
            placeholder="e.g. 100000"
            required
          />
          <Text fw={600} mt={8}>
            Map to Customer or Supplier
          </Text>
          <Group>
            <Select
              label="Customer"
              value={selectedCustomer}
              onChange={(value) => {
                setSelectedCustomer(value || "");
                setSelectedSupplier("");
                // Set debit/credit account to include customer name for mapping
                if (value) {
                  setDebitAccount(`Customer: ${value}`);
                  setCreditAccount("");
                } else {
                  setDebitAccount("");
                }
              }}
              data={customers.map((c) => ({ value: c.name, label: c.name }))}
              searchable
              clearable
              placeholder="Select customer"
            />
            <Select
              label="Supplier"
              value={selectedSupplier}
              onChange={(value) => {
                setSelectedSupplier(value || "");
                setSelectedCustomer("");
                // Set debit/credit account to include supplier name for mapping
                if (value) {
                  setCreditAccount(`Supplier: ${value}`);
                  setDebitAccount("");
                } else {
                  setCreditAccount("");
                }
              }}
              data={suppliers.map((s) => ({ value: s.name, label: s.name }))}
              searchable
              clearable
              placeholder="Select supplier"
            />
          </Group>
          {selectedCustomer && (
            <Text c="dimmed" size="sm">
              Balance:{" "}
              {(() => {
                const c = customers.find((x) => x.name === selectedCustomer);
                if (!c) return "N/A";
                const bal = c.openingAmount ?? 0;
                return `${bal < 0 ? "Debit" : "Credit"} ${Math.abs(bal)}`;
              })()}
            </Text>
          )}
          {selectedSupplier && (
            <Text c="dimmed" size="sm">
              Balance:{" "}
              {(() => {
                const s = suppliers.find((x) => x.name === selectedSupplier);
                if (!s) return "N/A";
                const bal = s.openingBalance ?? 0;
                return `${bal < 0 ? "Debit" : "Credit"} ${Math.abs(bal)}`;
              })()}
            </Text>
          )}
          <TextInput
            label="Debit Account"
            value={debitAccount}
            onChange={(e) => setDebitAccount(e.currentTarget.value)}
            placeholder="e.g. Accounts Receivable"
            required
          />
          <TextInput
            label="Credit Account"
            value={creditAccount}
            onChange={(e) => setCreditAccount(e.currentTarget.value)}
            placeholder="e.g. Accounts Payable"
            required
          />
          <Button
            leftSection={<RefreshCw size={16} />}
            loading={loading}
            onClick={handleFrontendGenerate}
          >
            Auto-Generate Voucher
          </Button>
        </Stack>
      </Card>
      <Card>
        <Card.Section>
          <ScrollArea>
            <Table
              highlightOnHover
              withRowBorders
              withColumnBorders
              withTableBorder
            >
              <Table.Thead
                style={{ background: "var(--mantine-color-gray-1, #f8f9fa)" }}
              >
                <tr>
                  <th>Voucher No</th>
                  <th>Date</th>
                  <th>Particulars</th>
                  <th>Debit Account</th>
                  <th>Credit Account</th>
                  <th style={{ textAlign: "right" }}>Amount</th>
                  <th>Action</th>
                </tr>
              </Table.Thead>
              <tbody>
                {filtered.map((v) => (
                  <tr key={v.id}>
                    <td style={{ fontFamily: "monospace", fontSize: 12 }}>
                      {v.voucherNumber}
                    </td>
                    <td>{formatDate(v.voucherDate)}</td>
                    <td>{v.particulars}</td>
                    <td>{v.debitAccount}</td>
                    <td>{v.creditAccount}</td>
                    <td style={{ textAlign: "right", fontWeight: 600 }}>
                      {formatCurrency(v.amount)}
                    </td>
                    <td>
                      <Button
                        size="xs"
                        variant="subtle"
                        leftSection={<MoreVertical size={16} />}
                        onClick={() => {
                          const invoiceData: InvoiceData = {
                            title: "Journal Voucher",
                            companyName: "Seven Star Traders",
                            addressLines: [
                              "Nasir Gardezi Road, Chowk Fawara, Bohar Gate Multan",
                            ],
                            invoiceNo: v.voucherNumber,
                            date:
                              typeof v.voucherDate === "string"
                                ? v.voucherDate
                                : v.voucherDate.toISOString(),
                            items: [
                              {
                                sr: 1,
                                section: `Particulars: ${v.particulars}`,
                                amount: v.amount,
                              },
                            ],
                            totals: { total: v.amount },
                            footerNotes: [
                              "Journal voucher generated by Aluminium POS",
                            ],
                          };
                          openPrintWindow(invoiceData);
                        }}
                      >
                        Print
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </ScrollArea>
        </Card.Section>
      </Card>
    </div>
  );
}
